version: 2

updates:
  - package-ecosystem: gomod
    directory: /devices/sbom
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(sbom)"
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
          - "github.com/aws/aws-lambda-go"
          - "github.com/aws/smithy-go"
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directory: /devices/sbom/terraform
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(sbom-tf)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
