#!/usr/bin/env bash
# SPDX SBOM Collection Script for Device Inventory
# Supports production mode (upload to Lambda) and test mode (local output)
#
# Usage:
#   sbom-audit-spdx                    # Production mode (monthly upload to Lambda)
#   sbom-audit-spdx --test             # Test mode (local output)
#   sbom-audit-spdx clean INPUT OUT    # Clean SPDX file for conversion
#   sbom-audit-spdx --help             # Show help

set -euo pipefail

# === Configuration ===
# Lambda URL - must be set via SBOM_LAMBDA_URL environment variable
LAMBDA_URL="${SBOM_LAMBDA_URL:-}"

# Device ID (from hostname, sanitized to prevent header injection / path traversal)
DEVICE_ID="${HOSTNAME:-$(hostname)}"
DEVICE_ID="${DEVICE_ID//[^a-zA-Z0-9._-]/}"
if [ -z "$DEVICE_ID" ]; then
	echo "✗ Could not determine a valid device ID from hostname" >&2
	exit 1
fi

# Timestamp for filenames
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)

# Detect primary macOS user (for Nix profile scanning when running as root via MDM)
if [ "$(id -u)" -eq 0 ]; then
	CONSOLE_USER=$(stat -f '%Su' /dev/console 2>/dev/null || echo "")
	if [ -n "$CONSOLE_USER" ] && [ "$CONSOLE_USER" != "root" ]; then
		CONSOLE_USER_HOME=$(dscl . -read "/Users/$CONSOLE_USER" NFSHomeDirectory 2>/dev/null | awk '{print $2}')
	else
		CONSOLE_USER_HOME="$HOME"
	fi
else
	CONSOLE_USER_HOME="$HOME"
fi

# === Mode Detection ===
MODE="production"
TEST_OUTPUT_DIR=""
FORCE_RUN="false"

# Strict deletion guardrail function
safe_delete_file() {
	local file_path="$1"

	# Verify file exists and is a regular file
	if [ ! -f "$file_path" ]; then
		return 0
	fi

	# Verify file is within SBOM_DIR
	local file_dir
	file_dir=$(dirname "$(realpath "$file_path" 2>/dev/null || echo "$file_path")")
	local sbom_realpath
	sbom_realpath=$(realpath "$SBOM_DIR" 2>/dev/null || echo "$SBOM_DIR")

	# Must be exactly SBOM_DIR or a subdirectory (not just prefix match)
	if [[ "$file_dir" != "$sbom_realpath" && "$file_dir" != "$sbom_realpath"/* ]]; then
		echo "✗ SAFETY: Refusing to delete file outside SBOM_DIR: $file_path" >&2
		return 1
	fi

	# Only delete files matching our patterns
	local basename
	basename=$(basename "$file_path")
	# Whitelist the exact filename patterns we create. The trailing
	# `(\.tmp\.[0-9]+)?` covers the partial-SBOM temp files generated by
	# generate_system_sbom; everything else must match exactly.
	if [[ "$basename" =~ ^(nix-.*\.spdx\.json|system-.*\.spdx\.json(\.tmp\.[0-9]+)?|device-.*\.spdx\.json|nix-pkg-[0-9]+-.*\.spdx\.json|sbom\.(cdx\.json|csv)|http_cache\.sqlite)$ ]]; then
		rm -f "$file_path"
		return 0
	else
		echo "✗ SAFETY: Refusing to delete unrecognized file pattern: $file_path" >&2
		return 1
	fi
}

format_bytes() {
	local bytes="$1"
	if command -v numfmt &>/dev/null; then
		numfmt --to=iec-i --suffix=B "$bytes" 2>/dev/null
	elif command -v gnumfmt &>/dev/null; then
		gnumfmt --to=iec-i --suffix=B "$bytes" 2>/dev/null
	else
		echo "${bytes} bytes"
	fi
}

# Handle subcommands first
if [ "${1:-}" = "clean" ]; then
	if [ $# -ne 3 ]; then
		echo "Usage: $0 clean <input.spdx.json> <output.spdx.json>" >&2
		exit 1
	fi

	CLEAN_INPUT="$2"
	CLEAN_OUTPUT="$3"

	echo "=== SPDX Cleanup Utility ==="
	echo "Input:  $CLEAN_INPUT"
	echo "Output: $CLEAN_OUTPUT"
	echo ""

	if [ ! -f "$CLEAN_INPUT" ]; then
		echo "✗ Input file not found: $CLEAN_INPUT" >&2
		exit 1
	fi

	# Use temporary file for atomic writes (prevents partial output on disk full)
	tmp_out="${CLEAN_OUTPUT}.tmp.$$"
	trap 'rm -f "$tmp_out"' EXIT INT TERM

	echo "Cleaning SPDX document..."
	echo "  - Removing files[] and cleaning dangling file references"
	echo "  - Deduplicating hasExtractedLicensingInfos[]"
	echo "  - Adding filesAnalyzed: false to packages"
	echo "  - Removing file-dependent fields (licenseInfoFromFiles, packageVerificationCode, hasFiles)"
	echo "  - Removing empty versionInfo fields"
	echo "  - Removing CPE externalRefs (cpe23Type)"
	jq '
        # Capture file SPDX IDs before deleting files
        ([.files[]?.SPDXID] | map(select(. != null))) as $file_ids |
        del(.files) |
        # Remove relationships referencing deleted file elements
        if .relationships then
            .relationships |= map(select(
                (.spdxElementId | IN($file_ids[]) | not) and
                (.relatedSpdxElement | IN($file_ids[]) | not)
            ))
            | if .relationships == [] then del(.relationships) else . end
        else . end |
        # Remove documentDescribes entries referencing deleted file elements
        if .documentDescribes then
            .documentDescribes |= map(select(IN($file_ids[]) | not))
            | if .documentDescribes == [] then del(.documentDescribes) else . end
        else . end |
        # Deduplicate hasExtractedLicensingInfos (case-sensitive, no normalization)
        if .hasExtractedLicensingInfos then
            .hasExtractedLicensingInfos |= (group_by(.licenseId) | map(.[0]))
        else . end |
        # Clean packages
        if (.packages | type) == "array" then
            .packages |= map(
                .filesAnalyzed = false |
                del(.licenseInfoFromFiles, .packageVerificationCode, .hasFiles) |
                if .versionInfo == "" then del(.versionInfo) else . end |
                if .externalRefs then
                    .externalRefs |= map(select(.referenceType != "cpe23Type"))
                else . end |
                if .externalRefs == [] then del(.externalRefs) else . end
            )
        else . end' \
		"$CLEAN_INPUT" >"$tmp_out"

	# Atomic rename on success
	mv "$tmp_out" "$CLEAN_OUTPUT"

	ORIG_SIZE=$(wc -c <"$CLEAN_INPUT" | tr -d ' ')
	NEW_SIZE=$(wc -c <"$CLEAN_OUTPUT" | tr -d ' ')
	PKG_COUNT=$(jq '.packages | length' "$CLEAN_OUTPUT" 2>/dev/null || echo "0")
	LICENSE_COUNT=$(jq '.hasExtractedLicensingInfos | length' "$CLEAN_OUTPUT" 2>/dev/null || echo "0")

	ORIG_FMT=$(format_bytes "$ORIG_SIZE")
	NEW_FMT=$(format_bytes "$NEW_SIZE")

	echo "✓ Cleaned SPDX document"
	echo "  Original size: $ORIG_FMT"
	echo "  Cleaned size: $NEW_FMT"
	echo "  Packages: $PKG_COUNT"
	echo "  Licenses: $LICENSE_COUNT (deduplicated)"
	echo "  Removed: files[], licenseInfoFromFiles, packageVerificationCode, hasFiles, cpe23Type refs"
	echo ""
	echo "✓ Output saved to: $CLEAN_OUTPUT"
	exit 0
fi

# Handle flags (parse all arguments to detect conflicts)
for arg in "$@"; do
	case "$arg" in
	--test)
		MODE="test"
		;;
	--test-upload)
		MODE="test-upload"
		;;
	--force)
		FORCE_RUN="true"
		;;
	--help | -h)
		MODE="help"
		;;
	esac
done

# Handle help flag
if [ "$MODE" = "help" ]; then
	cat <<'EOF'
SPDX SBOM Collection Script

Usage:
  sbom-audit-spdx                    # Production mode (monthly upload)
  sbom-audit-spdx --test             # Test mode (output to TMPDIR)
  sbom-audit-spdx --test-upload      # Test mode + upload to Lambda
  sbom-audit-spdx --force            # Force production run (bypass monthly check)
  sbom-audit-spdx clean INPUT OUT    # Clean SPDX file (utility)
  sbom-audit-spdx --help             # Show this help

Production Mode:
  - Checks if already run this month (exits if yes)
  - Scans Nix packages (sbomnix) and system packages (Syft)
  - Targets package manager directories (Homebrew, MacPorts, /usr/local)
  - Merges and deduplicates packages
  - Uploads to Lambda via presigned S3 URL
  - Creates monthly marker file

Test Mode (--test):
  - Outputs to $TMPDIR/sbom-test-TIMESTAMP/ (or /tmp if TMPDIR not set)
  - Scans Homebrew Cellar directory only for speed
  - Skips upload to Lambda
  - Preserves all intermediate files
  - Shows SBOM validation summary

Test Upload Mode (--test-upload):
  - Same as --test but also uploads to Lambda
  - Requires SBOM_LAMBDA_URL and SBOM_AUTH_TOKEN
  - Useful for testing the full end-to-end flow

Force Mode (--force):
  - Runs production mode even if already run this month
  - Useful for manual re-runs or troubleshooting
  - Requires SBOM_LAMBDA_URL and SBOM_AUTH_TOKEN

Clean Utility (clean):
  - Standalone utility to clean existing SPDX files
  - Removes files[] array and dangling file references
  - Deduplicates hasExtractedLicensingInfos[]
  - Removes file-dependent fields (licenseInfoFromFiles, packageVerificationCode, hasFiles)
  - Removes CPE externalRefs (cpe23Type)
  - Useful for SPDX conversion tools
  - Works independently of production/test modes

Environment Variables:
  SBOM_LAMBDA_URL - Lambda Function URL (required for production mode, set via MDM)
  SBOM_AUTH_TOKEN - Authentication token (required for production mode, set via MDM)

Examples:
  # Monthly production run (via MDM)
  sbom-audit-spdx

  # Test generation locally
  sbom-audit-spdx --test

  # Test end-to-end flow (generate + upload)
  SBOM_LAMBDA_URL='https://...' SBOM_AUTH_TOKEN='...' sbom-audit-spdx --test-upload

  # Clean SPDX file for conversion
  sbom-audit-spdx clean input.spdx.json cleaned.spdx.json
EOF
	exit 0
fi

# Validate flag combinations
if [[ "$MODE" == test* ]] && [ "$FORCE_RUN" = "true" ]; then
	echo "✗ Cannot use --test/--test-upload and --force together" >&2
	echo "  --test mode is for local testing" >&2
	echo "  --force mode is for production with monthly throttle bypass" >&2
	exit 1
fi

# Show force mode warning
if [ "$FORCE_RUN" = "true" ] && [ "$MODE" != "test" ]; then
	echo "⚠ Force mode enabled - bypassing monthly throttle check"
fi

# Set working directory based on mode. The `-m 700` applies to the leaf
# directory; parent dirs ($TMPDIR or $HOME) are pre-existing and not our
# concern, so SC2174's caveat doesn't apply here.
if [[ "$MODE" == test* ]]; then
	# Use tmpdir for test output to avoid hardcoding user paths
	TEST_OUTPUT_DIR="${TMPDIR:-/tmp}/sbom-test-${TIMESTAMP}"
	# shellcheck disable=SC2174
	mkdir -p -m 700 "$TEST_OUTPUT_DIR"
	SBOM_DIR="$TEST_OUTPUT_DIR"
else
	SBOM_DIR="${HOME}/.sbom-audit"
	# shellcheck disable=SC2174
	mkdir -p -m 700 "$SBOM_DIR"
fi

# === Helper Functions ===

check_already_run() {
	if [[ "$MODE" == test* ]] || [ "$FORCE_RUN" = "true" ]; then
		# Skip monthly check in test mode or when forced
		return 0
	fi

	# Check if we've already run this month
	local current_month
	current_month=$(date -u +%Y-%m)

	# Find any marker files from this month
	if find "$SBOM_DIR" -name ".last-upload-${current_month}*" -type f 2>/dev/null | grep -q .; then
		echo "✓ SBOM already uploaded this month ($current_month)"
		exit 0
	fi
}

# Set by detect_brew. Empty until a brew install is found.
BREW_BIN=""
# "workbrew" (MDM-managed, may run as root) or "homebrew" (refuses root).
BREW_FLAVOR=""

# Detect an existing brew installation and set BREW_BIN / BREW_FLAVOR / PATH
# explicitly. Returns 0 if found, 1 otherwise. Avoids `eval $(brew shellenv)`
# which would execute whatever the binary chose to emit — risky as root.
detect_brew() {
	local prefix=""
	if [ -x /opt/workbrew/bin/brew ]; then
		BREW_BIN="/opt/workbrew/bin/brew"
		BREW_FLAVOR="workbrew"
		prefix="/opt/workbrew"
	elif [ -x /opt/homebrew/bin/brew ]; then
		BREW_BIN="/opt/homebrew/bin/brew"
		BREW_FLAVOR="homebrew"
		prefix="/opt/homebrew"
	elif [ -x /usr/local/bin/brew ]; then
		BREW_BIN="/usr/local/bin/brew"
		BREW_FLAVOR="homebrew"
		prefix="/usr/local"
	else
		return 1
	fi

	export PATH="${prefix}/bin:${prefix}/sbin:${PATH}"
	export HOMEBREW_PREFIX="${prefix}"
	return 0
}

# Run a command in the user context that matches the active brew flavour.
# Workbrew is MDM-managed and accepts root; vanilla Homebrew refuses root,
# so drop to the logged-in console user via sudo when running as root. This
# applies not only to `brew` itself but to anything brew installs (pipx,
# python tools, etc.) — running them as their installer keeps the install
# and invocation in the same user context and avoids cross-user TOCTOU on
# Homebrew-managed binaries.
as_brew_user() {
	if [ "$(id -u)" -ne 0 ] || [ "$BREW_FLAVOR" = "workbrew" ]; then
		"$@"
		return $?
	fi

	# Homebrew + running as root. Drop to console user.
	if [ -z "${CONSOLE_USER:-}" ] || [ "$CONSOLE_USER" = "root" ]; then
		echo "✗ Cannot run a brew-managed tool as root without a console user." >&2
		echo "  This device should have Workbrew installed for MDM-managed use." >&2
		return 1
	fi
	sudo -u "$CONSOLE_USER" -H "$@"
}

# Invoke brew in the right user context. Wraps as_brew_user with the
# detected brew binary path.
brew_run() {
	if [ -z "$BREW_BIN" ]; then
		echo "✗ brew_run called before detect_brew succeeded" >&2
		return 1
	fi
	as_brew_user "$BREW_BIN" "$@"
}

ensure_homebrew() {
	# Prefer an existing installation. Workbrew is the MDM-managed brew
	# flavour and is expected to be pre-installed via the fleet config;
	# the script does not attempt to install Workbrew itself. If neither
	# is present, install Homebrew as a fallback so dependent packages
	# (jq, syft, etc.) can be installed.
	if detect_brew; then
		echo "✓ Using ${BREW_FLAVOR} at ${BREW_BIN}"
		return 0
	fi

	echo "✓ Neither Workbrew nor Homebrew found — installing Homebrew..."

	# Homebrew's installer refuses root. When running as root (MDM
	# MDM context), invoke the installer as the logged-in console user.
	if [ "$(id -u)" -eq 0 ]; then
		if [ -z "${CONSOLE_USER:-}" ] || [ "$CONSOLE_USER" = "root" ]; then
			echo "✗ Cannot install Homebrew as root with no console user." >&2
			echo "  Install Workbrew via MDM for managed devices, or" >&2
			echo "  install Homebrew manually for the device's primary user." >&2
			return 1
		fi
		if ! sudo -u "$CONSOLE_USER" -H /bin/bash -c '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'; then
			echo "✗ Homebrew install failed (as $CONSOLE_USER)" >&2
			return 1
		fi
	else
		if ! /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; then
			echo "✗ Homebrew install failed" >&2
			return 1
		fi
	fi

	if detect_brew; then
		echo "✓ Homebrew installed at ${BREW_BIN}"
		return 0
	fi

	echo "✗ Homebrew install reported success but no brew binary found" >&2
	return 1
}

ensure_jq() {
	if command -v jq &>/dev/null; then
		return 0
	fi

	echo "✓ Installing jq..."
	if [ -n "$BREW_BIN" ]; then
		brew_run install jq
		return $?
	fi

	echo "✗ jq is not installed and Homebrew is not available to install it" >&2
	return 1
}

ensure_gnumfmt() {
	# Check if numfmt is available (GNU coreutils)
	if command -v numfmt &>/dev/null; then
		return 0
	fi

	# On macOS, install GNU coreutils for gnumfmt
	if [[ "$(uname)" == "Darwin" ]]; then
		echo "✓ Installing GNU coreutils (for numfmt)..."
		if [ -n "$BREW_BIN" ]; then
			brew_run install coreutils
			return $?
		fi
	fi

	# Fall back to basic formatting if not available
	return 1
}

ensure_syft() {
	if [ -z "$BREW_BIN" ]; then
		if command -v syft &>/dev/null; then
			echo "  ⚠ Syft installed but brew not available for upgrades"
			return 0
		fi
		echo "✗ Syft is not installed and Homebrew is not available to install it" >&2
		return 1
	fi

	if command -v syft &>/dev/null; then
		echo "✓ Upgrading Syft..."
		# Don't mask failures — they may indicate tap compromise, network
		# issues, or a refuse-to-run-as-root response. Warn but continue
		# with the existing installed version rather than aborting the run.
		if ! brew_run upgrade syft; then
			echo "  ⚠ syft upgrade failed; continuing with existing version" >&2
		fi
		return 0
	fi

	echo "✓ Installing Syft..."
	brew_run install syft
	return $?
}

ensure_sbomnix() {
	if command -v sbomnix &>/dev/null; then
		return 0
	fi

	# Nix is required
	if ! command -v nix &>/dev/null; then
		echo "✗ Nix not available - required for sbomnix" >&2
		return 1
	fi

	echo "✓ Installing sbomnix..."
	nix profile add github:tiiuae/sbomnix --accept-flake-config || {
		echo "✗ sbomnix install failed" >&2
		return 1
	}

	# `nix profile add` installs into ~/.nix-profile/bin, but MDM runs
	# scripts non-interactively so /etc/profile.d/nix.sh is never sourced
	# and that directory is not on PATH. Without this step, the install
	# silently succeeds but the next `sbomnix` invocation falls into the
	# `|| continue` branch in generate_nix_sbom, producing an empty Nix
	# SBOM with no operator-visible error.
	local nix_bin
	for nix_bin in \
		"${HOME}/.nix-profile/bin" \
		"/nix/var/nix/profiles/per-user/$(id -un)/profile/bin" \
		"/nix/var/nix/profiles/default/bin"; do
		if [ -x "${nix_bin}/sbomnix" ]; then
			export PATH="${nix_bin}:${PATH}"
			break
		fi
	done

	if ! command -v sbomnix &>/dev/null; then
		echo "✗ sbomnix installed by 'nix profile add' but not found on PATH" >&2
		echo "  Searched: \$HOME/.nix-profile/bin, /nix/var/nix/profiles/per-user/\$(id -un)/profile/bin, /nix/var/nix/profiles/default/bin" >&2
		return 1
	fi
	return 0
}

ensure_pyspdxtools() {
	# pipx installs binaries into the user's ~/.local/bin. The "user" here
	# depends on the brew flavour: Workbrew runs as root → /var/root/.local/bin,
	# Homebrew runs as the console user → ${CONSOLE_USER_HOME}/.local/bin.
	# Resolve the correct path once.
	local pipx_bin
	if [ "$(id -u)" -eq 0 ] && [ "$BREW_FLAVOR" = "homebrew" ] && [ -n "${CONSOLE_USER:-}" ] && [ "$CONSOLE_USER" != "root" ]; then
		pipx_bin="${CONSOLE_USER_HOME}/.local/bin"
	else
		pipx_bin="${HOME}/.local/bin"
	fi

	if ! command -v pyspdxtools &>/dev/null && [ -x "${pipx_bin}/pyspdxtools" ]; then
		export PATH="${pipx_bin}:${PATH}"
	fi

	if command -v pyspdxtools &>/dev/null; then
		return 0
	fi

	echo "✓ Installing pyspdxtools (SPDX validator)..."
	if [ -n "$BREW_BIN" ]; then
		# Both steps run in the same user context as the brew that installs
		# pipx — keeps the install and invocation in one user and avoids
		# cross-user TOCTOU on the Homebrew-installed pipx binary.
		if ! brew_run install pipx; then
			echo "✗ pipx install via brew failed" >&2
			return 1
		fi
		if ! as_brew_user pipx install spdx-tools; then
			echo "✗ pipx install spdx-tools failed" >&2
			return 1
		fi
		if [ -x "${pipx_bin}/pyspdxtools" ]; then
			export PATH="${pipx_bin}:${PATH}"
			return 0
		fi
	fi

	return 1
}

validate_spdx() {
	local spdx_file="$1"

	if ! command -v pyspdxtools &>/dev/null; then
		echo "  ✗ pyspdxtools not available - cannot validate" >&2
		return 1
	fi

	echo "→ Validating SPDX document..."

	local validation_output
	validation_output=$(pyspdxtools -i "$spdx_file" 2>&1)
	local exit_code=$?

	if [ $exit_code -eq 0 ]; then
		echo "  ✓ SPDX validation passed"
		return 0
	else
		echo "  ✗ SPDX validation failed" >&2
		echo "$validation_output" | tail -20 >&2
		return 1
	fi
}

generate_nix_sbom() {
	# Ensure sbomnix is available (required)
	ensure_sbomnix || {
		echo "✗ sbomnix is required but not available" >&2
		return 1
	}

	local output_file="$1"
	local nix_sboms=()

	echo "→ Scanning Nix packages..."

	# Scan user profile packages (from nix profile list)
	if command -v nix &>/dev/null && [ -e "${CONSOLE_USER_HOME}/.nix-profile" ]; then
		echo "  → Scanning Nix profile packages..."

		# Get store paths from profile
		# When running as root (via MDM/sudo), query the console user's profile
		local store_paths
		if [ "$(id -u)" -eq 0 ] && [ -n "${CONSOLE_USER:-}" ] && [ "$CONSOLE_USER" != "root" ]; then
			store_paths=$(sudo -u "$CONSOLE_USER" nix profile list 2>/dev/null | grep "Store paths:" | awk '{print $3}')
		else
			store_paths=$(nix profile list 2>/dev/null | grep "Store paths:" | awk '{print $3}')
		fi

		if [ -z "$store_paths" ]; then
			echo "  ✗ No Nix store paths found in profile (nix profile list output may have changed)" >&2
			echo "  → Skipping Nix package scan (non-fatal)" >&2
		fi

		if [ -n "$store_paths" ]; then
			local path_count=0
			while IFS= read -r store_path; do
				if [ -n "$store_path" ] && [ -e "$store_path" ]; then
					local pkg_name
					pkg_name=$(basename "$store_path" | cut -d'-' -f2-)
					echo "    → Scanning: $pkg_name"

					local pkg_sbom="${SBOM_DIR}/nix-pkg-${path_count}-${TIMESTAMP}.spdx.json"

					# Run sbomnix in SBOM_DIR to contain output files
					(cd "$SBOM_DIR" && sbomnix "$store_path" --spdx "$pkg_sbom" 2>/dev/null) || {
						safe_delete_file "$pkg_sbom"
						continue
					}

					# Validate sbomnix produced valid SPDX output
					if [ -f "$pkg_sbom" ] && jq -e '.spdxVersion' "$pkg_sbom" >/dev/null 2>&1; then
						nix_sboms+=("$pkg_sbom")
						# Clean up extra outputs sbomnix creates
						safe_delete_file "${SBOM_DIR}/sbom.cdx.json"
						safe_delete_file "${SBOM_DIR}/sbom.csv"
						safe_delete_file "${SBOM_DIR}/http_cache.sqlite"
						path_count=$((path_count + 1))
					else
						echo "    ⚠ sbomnix produced invalid SPDX for $pkg_name (skipping)" >&2
						safe_delete_file "$pkg_sbom"
					fi
				fi
			done <<<"$store_paths"

			if [ $path_count -gt 0 ]; then
				echo "  ✓ Scanned $path_count profile package(s)"
			else
				echo "  ⚠ No profile packages could be scanned"
			fi
		else
			echo "  ⚠ No packages in profile"
		fi
	fi

	# If we have Nix SBOMs, merge them
	if [ ${#nix_sboms[@]} -gt 0 ]; then
		echo "  → Merging ${#nix_sboms[@]} Nix SBOM(s)..."

		# Merge packages from all Nix SBOMs, deduplicate licenses, remove CPE refs
		if ! jq -s '{
                SPDXID: "SPDXRef-DOCUMENT",
                spdxVersion: "SPDX-2.3",
                creationInfo: (.[0].creationInfo // {created: (now | strftime("%Y-%m-%dT%H:%M:%SZ"))}),
                name: (.[0].name // "nix-packages"),
                dataLicense: "CC0-1.0",
                documentNamespace: (.[0].documentNamespace // ""),
                hasExtractedLicensingInfos: (
                    [.[].hasExtractedLicensingInfos[]?] |
                    group_by(.licenseId) | map(.[0])
                ),
                packages: ([.[].packages[]?] | unique_by(.SPDXID // (.name + "-" + (.versionInfo // "UNKNOWN") + "-" + (.downloadLocation // "UNKNOWN"))) | 
                           map(
                               .filesAnalyzed = false |
                               del(.licenseInfoFromFiles, .packageVerificationCode, .hasFiles) |
                               if .versionInfo == "" then del(.versionInfo) else . end |
                               if .externalRefs then
                                   .externalRefs |= map(select(.referenceType != "cpe23Type"))
                               else . end |
                               if .externalRefs == [] then del(.externalRefs) else . end
                           ))
            } | if .hasExtractedLicensingInfos == [] then del(.hasExtractedLicensingInfos) else . end
        ' "${nix_sboms[@]}" >"$output_file"; then
			echo "  ✗ jq merge failed for Nix SBOMs" >&2
			return 1
		fi

		if [ ! -s "$output_file" ]; then
			echo "  ✗ jq produced empty output for Nix SBOMs" >&2
			return 1
		fi

		local pkg_count
		pkg_count=$(jq '.packages | length' "$output_file" 2>/dev/null || echo "0")
		echo "  ✓ Merged Nix SBOM: $pkg_count packages"

		if [[ "$MODE" == test* ]]; then
			echo "  ✓ Saved to: $output_file"
		fi

		return 0
	else
		# No Nix packages found, but sbomnix ran successfully
		# Create empty SBOM to satisfy the requirement
		echo "  ⚠ No Nix packages found (profile and projects empty)"
		echo '{"SPDXID":"SPDXRef-DOCUMENT","spdxVersion":"SPDX-2.3","name":"nix-packages","dataLicense":"CC0-1.0","documentNamespace":"http://spdx.org/spdxdocs/empty","packages":[],"relationships":[]}' >"$output_file"
		return 0
	fi
}

generate_system_sbom() {
	local output_file="$1"
	local temp_file="${output_file}.tmp"

	# Determine scan paths based on mode
	# Use inclusive scan: target specific package manager directories instead of
	# scanning all of / with exclusions. Scanning / is too slow — Syft indexes the
	# entire filesystem before applying excludes, so it walks through every dev
	# project, node_modules, vendor dir, etc.
	local scan_paths=()
	if [[ "$MODE" == test* ]]; then
		echo "→ Scanning system packages (testing with Homebrew Cellar for speed)..."
		if [ -d "/opt/homebrew/Cellar" ]; then
			scan_paths+=("/opt/homebrew/Cellar")
		elif [ -d "/usr/local/Cellar" ]; then
			scan_paths+=("/usr/local/Cellar")
		else
			echo "✗ Test mode requires Homebrew (not found at /opt/homebrew or /usr/local)" >&2
			exit 1
		fi
	else
		echo "→ Scanning system packages (package manager directories)..."

		# === Homebrew prefix ===
		# Scan the entire prefix — covers Cellar (formulae), Caskroom (casks),
		# lib/python*/site-packages, lib/node_modules, lib/ruby/gems,
		# lib/php/pecl, lib/erlang/lib, lib/luarocks, share/lua, bin/, etc.
		# Syft has catalogers for all of these.
		[ -d "/opt/homebrew" ] && scan_paths+=("/opt/homebrew")
		# Intel Mac: /usr/local is the Homebrew prefix (also catches standalone installs)
		[ -d "/usr/local" ] && scan_paths+=("/usr/local")

		# Workbrew (enterprise Homebrew — separate prefix)
		[ -d "/opt/workbrew" ] && scan_paths+=("/opt/workbrew")

		# MacPorts
		[ -d "/opt/local" ] && scan_paths+=("/opt/local")

		# === System frameworks ===
		[ -d "/Library/Frameworks/Python.framework" ] && scan_paths+=("/Library/Frameworks/Python.framework")
		[ -d "/Library/Frameworks/R.framework" ] && scan_paths+=("/Library/Frameworks/R.framework")
		[ -d "/Library/Ruby/Gems" ] && scan_paths+=("/Library/Ruby/Gems")
		[ -d "/Library/Java/Extensions" ] && scan_paths+=("/Library/Java/Extensions")

		# NOTE: /usr/local/go and /usr/local/share/dotnet are covered by /usr/local above

		# === User-level package managers ===
		# Python (pip user installs, pipx)
		[ -d "${CONSOLE_USER_HOME}/Library/Python" ] && scan_paths+=("${CONSOLE_USER_HOME}/Library/Python")
		for d in "${CONSOLE_USER_HOME}"/.local/lib/python*/; do [ -d "$d" ] && scan_paths+=("$d"); done
		[ -d "${CONSOLE_USER_HOME}/.local/pipx" ] && scan_paths+=("${CONSOLE_USER_HOME}/.local/pipx")

		# Ruby (user gems)
		[ -d "${CONSOLE_USER_HOME}/.gem" ] && scan_paths+=("${CONSOLE_USER_HOME}/.gem")

		# Go — only scan bin/ (compiled binaries with embedded module info).
		# Skip pkg/mod/ (module cache) which can be tens of GB of source code.
		[ -d "${CONSOLE_USER_HOME}/go/bin" ] && scan_paths+=("${CONSOLE_USER_HOME}/go/bin")

		# Rust (cargo-auditable binaries, registry)
		[ -d "${CONSOLE_USER_HOME}/.cargo" ] && scan_paths+=("${CONSOLE_USER_HOME}/.cargo")

		# Node.js (nvm-managed versions, global installs)
		[ -d "${CONSOLE_USER_HOME}/.nvm" ] && scan_paths+=("${CONSOLE_USER_HOME}/.nvm")
		[ -d "${CONSOLE_USER_HOME}/.npm-global" ] && scan_paths+=("${CONSOLE_USER_HOME}/.npm-global")
		[ -d "${CONSOLE_USER_HOME}/.config/yarn/global" ] && scan_paths+=("${CONSOLE_USER_HOME}/.config/yarn/global")

		# pnpm global
		[ -d "${CONSOLE_USER_HOME}/Library/pnpm" ] && scan_paths+=("${CONSOLE_USER_HOME}/Library/pnpm")

		# Java (Maven local repo, Gradle cache, SDKMAN, Coursier)
		[ -d "${CONSOLE_USER_HOME}/.m2" ] && scan_paths+=("${CONSOLE_USER_HOME}/.m2")
		[ -d "${CONSOLE_USER_HOME}/.gradle/caches" ] && scan_paths+=("${CONSOLE_USER_HOME}/.gradle/caches")
		[ -d "${CONSOLE_USER_HOME}/.sdkman/candidates" ] && scan_paths+=("${CONSOLE_USER_HOME}/.sdkman/candidates")
		[ -d "${CONSOLE_USER_HOME}/.cs" ] && scan_paths+=("${CONSOLE_USER_HOME}/.cs")
		[ -d "${CONSOLE_USER_HOME}/Library/Java/Extensions" ] && scan_paths+=("${CONSOLE_USER_HOME}/Library/Java/Extensions")

		# .NET (NuGet packages, dotnet tools/SDK)
		[ -d "${CONSOLE_USER_HOME}/.nuget" ] && scan_paths+=("${CONSOLE_USER_HOME}/.nuget")
		[ -d "${CONSOLE_USER_HOME}/.dotnet" ] && scan_paths+=("${CONSOLE_USER_HOME}/.dotnet")

		# PHP (global Composer packages)
		[ -d "${CONSOLE_USER_HOME}/.composer" ] && scan_paths+=("${CONSOLE_USER_HOME}/.composer")

		# Haskell (ghcup, cabal, stack)
		[ -d "${CONSOLE_USER_HOME}/.ghcup" ] && scan_paths+=("${CONSOLE_USER_HOME}/.ghcup")
		[ -d "${CONSOLE_USER_HOME}/.cabal" ] && scan_paths+=("${CONSOLE_USER_HOME}/.cabal")
		[ -d "${CONSOLE_USER_HOME}/.stack" ] && scan_paths+=("${CONSOLE_USER_HOME}/.stack")

		# Elixir / Erlang (hex, mix)
		[ -d "${CONSOLE_USER_HOME}/.hex" ] && scan_paths+=("${CONSOLE_USER_HOME}/.hex")
		[ -d "${CONSOLE_USER_HOME}/.mix" ] && scan_paths+=("${CONSOLE_USER_HOME}/.mix")

		# Dart (pub cache)
		[ -d "${CONSOLE_USER_HOME}/.pub-cache" ] && scan_paths+=("${CONSOLE_USER_HOME}/.pub-cache")

		# Lua (LuaRocks)
		[ -d "${CONSOLE_USER_HOME}/.luarocks" ] && scan_paths+=("${CONSOLE_USER_HOME}/.luarocks")

		# OCaml (opam)
		[ -d "${CONSOLE_USER_HOME}/.opam" ] && scan_paths+=("${CONSOLE_USER_HOME}/.opam")

		# C/C++ (Conan package manager)
		[ -d "${CONSOLE_USER_HOME}/.conan" ] && scan_paths+=("${CONSOLE_USER_HOME}/.conan")
		[ -d "${CONSOLE_USER_HOME}/.conan2" ] && scan_paths+=("${CONSOLE_USER_HOME}/.conan2")

		# Swift (SwiftPM)
		[ -d "${CONSOLE_USER_HOME}/.swiftpm" ] && scan_paths+=("${CONSOLE_USER_HOME}/.swiftpm")

		# CocoaPods (pod repos/cache)
		[ -d "${CONSOLE_USER_HOME}/.cocoapods" ] && scan_paths+=("${CONSOLE_USER_HOME}/.cocoapods")

		# R (user library)
		[ -d "${CONSOLE_USER_HOME}/Library/R" ] && scan_paths+=("${CONSOLE_USER_HOME}/Library/R")

		# Conda / Miniconda / Anaconda / Miniforge
		[ -d "${CONSOLE_USER_HOME}/miniconda3" ] && scan_paths+=("${CONSOLE_USER_HOME}/miniconda3")
		[ -d "${CONSOLE_USER_HOME}/anaconda3" ] && scan_paths+=("${CONSOLE_USER_HOME}/anaconda3")
		[ -d "${CONSOLE_USER_HOME}/miniforge3" ] && scan_paths+=("${CONSOLE_USER_HOME}/miniforge3")

		# Terraform (providers / plugins)
		[ -d "${CONSOLE_USER_HOME}/.terraform.d" ] && scan_paths+=("${CONSOLE_USER_HOME}/.terraform.d")

		# === Language version managers ===
		# These install full language runtimes (with their package ecosystems)
		# outside of Homebrew, so Syft's catalogers find pip packages inside
		# pyenv, gems inside rbenv, etc.

		# pyenv (Python versions + pip packages)
		[ -d "${CONSOLE_USER_HOME}/.pyenv" ] && scan_paths+=("${CONSOLE_USER_HOME}/.pyenv")

		# rbenv (Ruby versions + gems)
		[ -d "${CONSOLE_USER_HOME}/.rbenv" ] && scan_paths+=("${CONSOLE_USER_HOME}/.rbenv")

		# asdf (multi-language version manager)
		[ -d "${CONSOLE_USER_HOME}/.asdf" ] && scan_paths+=("${CONSOLE_USER_HOME}/.asdf")

		# mise / rtx (asdf-compatible version manager)
		[ -d "${CONSOLE_USER_HOME}/.local/share/mise" ] && scan_paths+=("${CONSOLE_USER_HOME}/.local/share/mise")

		# Volta (Node.js version manager + global packages)
		[ -d "${CONSOLE_USER_HOME}/.volta" ] && scan_paths+=("${CONSOLE_USER_HOME}/.volta")

		# fnm (fast Node.js version manager)
		[ -d "${CONSOLE_USER_HOME}/.local/share/fnm" ] && scan_paths+=("${CONSOLE_USER_HOME}/.local/share/fnm")
		[ -d "${CONSOLE_USER_HOME}/Library/Application Support/fnm" ] && scan_paths+=("${CONSOLE_USER_HOME}/Library/Application Support/fnm")

		# Deno (runtime + cached modules)
		[ -d "${CONSOLE_USER_HOME}/.deno" ] && scan_paths+=("${CONSOLE_USER_HOME}/.deno")

		# Bun (runtime + installed packages)
		[ -d "${CONSOLE_USER_HOME}/.bun" ] && scan_paths+=("${CONSOLE_USER_HOME}/.bun")

		# === Additional runtimes & tools ===

		# Perl (local::lib / cpanm)
		[ -d "${CONSOLE_USER_HOME}/perl5" ] && scan_paths+=("${CONSOLE_USER_HOME}/perl5")

		# Groovy / Grape
		[ -d "${CONSOLE_USER_HOME}/.groovy/grapes" ] && scan_paths+=("${CONSOLE_USER_HOME}/.groovy/grapes")

		# Scala (sbt, Coursier apps)
		[ -d "${CONSOLE_USER_HOME}/.sbt" ] && scan_paths+=("${CONSOLE_USER_HOME}/.sbt")
		[ -d "${CONSOLE_USER_HOME}/Library/Application Support/Coursier" ] && scan_paths+=("${CONSOLE_USER_HOME}/Library/Application Support/Coursier")

		# Kotlin (kotlin-native, kscript cache)
		[ -d "${CONSOLE_USER_HOME}/.kotlin" ] && scan_paths+=("${CONSOLE_USER_HOME}/.kotlin")

		# Juliaup / Julia packages
		[ -d "${CONSOLE_USER_HOME}/.julia" ] && scan_paths+=("${CONSOLE_USER_HOME}/.julia")

		# Zig (version manager installs)
		[ -d "${CONSOLE_USER_HOME}/.zig" ] && scan_paths+=("${CONSOLE_USER_HOME}/.zig")

		# Nim (nimble packages)
		[ -d "${CONSOLE_USER_HOME}/.nimble" ] && scan_paths+=("${CONSOLE_USER_HOME}/.nimble")

		# V (vlang modules)
		[ -d "${CONSOLE_USER_HOME}/.vmodules" ] && scan_paths+=("${CONSOLE_USER_HOME}/.vmodules")

		if [ ${#scan_paths[@]} -eq 0 ]; then
			echo "  ⚠ No known package manager directories found"
			echo '{"SPDXID":"SPDXRef-DOCUMENT","spdxVersion":"SPDX-2.3","name":"system-packages","dataLicense":"CC0-1.0","documentNamespace":"http://spdx.org/spdxdocs/empty","packages":[],"relationships":[]}' >"$output_file"
			return 0
		fi

		echo "  Scanning ${#scan_paths[@]} directories: ${scan_paths[*]}"
	fi

	# Scan each target directory with Syft and collect partial SBOMs
	local syft_errors="${SBOM_DIR}/syft-errors-${TIMESTAMP}.log"
	local syft_timeout=1800
	local partial_sboms=()
	local scan_idx=0

	for scan_path in "${scan_paths[@]}"; do
		echo "  → Scanning: $scan_path"
		local partial_file="${temp_file}.${scan_idx}"
		scan_idx=$((scan_idx + 1))

		# Retry loop: Syft's directory indexer treats ENOENT as fatal when transient
		# directories vanish mid-scan (anchore/syft#3286). Retry up to 3 times.
		local syft_max_retries=3
		local syft_attempt=0
		local syft_exit=1

		while [ "$syft_attempt" -lt "$syft_max_retries" ]; do
			syft_attempt=$((syft_attempt + 1))
			rm -f "$partial_file" "$syft_errors"

			if [ "$syft_attempt" -gt 1 ]; then
				echo "    → Retry $syft_attempt/$syft_max_retries..."
			fi

			SYFT_CHECK_FOR_APP_UPDATE=false taskpolicy -b syft scan "dir:$scan_path" \
				--source-name "$DEVICE_ID" \
				--source-version "$TIMESTAMP" \
				--output "spdx-json=$partial_file" \
				--exclude '**/.git/**' 2>"$syft_errors" &
			local syft_pid=$!
			(sleep "$syft_timeout" && kill "$syft_pid" 2>/dev/null) &
			local watchdog_pid=$!
			wait "$syft_pid" 2>/dev/null
			syft_exit=$?
			kill "$watchdog_pid" 2>/dev/null || true
			wait "$watchdog_pid" 2>/dev/null || true

			if [ "$syft_exit" -eq 0 ]; then
				break
			fi

			# Timeout — not retryable
			if ! kill -0 "$syft_pid" 2>/dev/null && [ "$syft_exit" -gt 128 ]; then
				echo "    ⚠ Syft scan timed out for $scan_path (skipping)" >&2
				break
			fi

			# Transient indexing error — retryable
			if [ -f "$syft_errors" ] && grep -q "no such file or directory" "$syft_errors" 2>/dev/null; then
				echo "    ⚠ Transient path error (attempt $syft_attempt/$syft_max_retries)" >&2
				continue
			fi

			# Non-transient failure
			echo "    ⚠ Syft scan failed for $scan_path (exit $syft_exit, skipping)" >&2
			if [ -f "$syft_errors" ] && [ -s "$syft_errors" ]; then
				tail -5 "$syft_errors" >&2
			fi
			break
		done

		rm -f "$syft_errors"

		if [ "$syft_exit" -eq 0 ] && [ -f "$partial_file" ] && [ -s "$partial_file" ]; then
			partial_sboms+=("$partial_file")
			local partial_pkg_count
			partial_pkg_count=$(jq '.packages | length' "$partial_file" 2>/dev/null || echo "?")
			echo "    ✓ $partial_pkg_count packages"
		else
			rm -f "$partial_file"
		fi
	done

	if [ ${#partial_sboms[@]} -eq 0 ]; then
		echo "✗ All Syft scans failed — no system packages found" >&2
		return 1
	fi

	# Merge partial SBOMs and clean SPDX output
	# - Remove files[] (too large)
	# - Deduplicate packages and hasExtractedLicensingInfos
	# - Remove file-dependent fields incompatible with filesAnalyzed=false
	# - Remove empty versionInfo fields
	# - Remove CPE externalRefs (cpe23Type)
	if ! jq -s '
        {
            SPDXID: .[0].SPDXID,
            spdxVersion: .[0].spdxVersion,
            creationInfo: .[0].creationInfo,
            name: .[0].name,
            dataLicense: .[0].dataLicense,
            documentNamespace: .[0].documentNamespace,
            hasExtractedLicensingInfos: (
                [.[].hasExtractedLicensingInfos[]?] |
                group_by(.licenseId) | map(.[0])
            ),
            packages: (
                [.[].packages[]?] |
                unique_by(.SPDXID // (.name + "-" + (.versionInfo // "UNKNOWN") + "-" + (.downloadLocation // "UNKNOWN"))) |
                map(
                    .filesAnalyzed = false |
                    del(.licenseInfoFromFiles, .packageVerificationCode, .hasFiles) |
                    if .versionInfo == "" then del(.versionInfo) else . end |
                    if .externalRefs then
                        .externalRefs |= map(select(.referenceType != "cpe23Type"))
                    else . end |
                    if .externalRefs == [] then del(.externalRefs) else . end
                )
            )
        } |
        del(.files) |
        if .hasExtractedLicensingInfos == [] then del(.hasExtractedLicensingInfos) else . end
    ' "${partial_sboms[@]}" >"$output_file"; then
		for f in "${partial_sboms[@]}"; do rm -f "$f"; done
		echo "  ✗ jq merge/processing failed for system SBOM" >&2
		return 1
	fi

	# Clean up partial files
	for f in "${partial_sboms[@]}"; do rm -f "$f"; done

	if [ ! -s "$output_file" ]; then
		echo "  ✗ jq produced empty output for system SBOM" >&2
		return 1
	fi

	local pkg_count
	pkg_count=$(jq '.packages | length' "$output_file" 2>/dev/null || echo "0")
	echo "  ✓ System scan complete: $pkg_count packages"

	if [[ "$MODE" == test* ]]; then
		echo "  ✓ Saved to: $output_file"
	fi

	return 0
}

generate_device_sbom() {
	local nix_sbom="${SBOM_DIR}/nix-${TIMESTAMP}.spdx.json"
	local system_sbom="${SBOM_DIR}/system-${TIMESTAMP}.spdx.json"
	local merged_sbom="${SBOM_DIR}/device-${DEVICE_ID}-${TIMESTAMP}.spdx.json"

	local sboms_to_merge=()

	# Generate Nix SBOM (required)
	if ! generate_nix_sbom "$nix_sbom" >&2; then
		echo "✗ Nix SBOM generation failed" >&2
		exit 1
	fi
	sboms_to_merge+=("$nix_sbom")

	# Generate system SBOM (required)
	if ! generate_system_sbom "$system_sbom" >&2; then
		echo "✗ System scan failed" >&2
		exit 1
	fi
	sboms_to_merge+=("$system_sbom")

	# Merge all SBOMs
	echo "" >&2
	echo "→ Merging SBOMs..." >&2

	if [ ${#sboms_to_merge[@]} -eq 1 ]; then
		# Only one SBOM, just copy it
		cp "${sboms_to_merge[0]}" "$merged_sbom"
		echo "  ✓ Single SBOM copied to final location" >&2
	else
		# Merge multiple SBOMs
		# Generate unique namespace for this document
		local doc_uuid
		if command -v uuidgen &>/dev/null; then
			doc_uuid=$(uuidgen | tr '[:upper:]' '[:lower:]')
		else
			# Fallback for the (unlikely) case uuidgen isn't on PATH.
			# documentNamespace is non-security-critical, so a deterministic
			# fallback is sufficient. `/proc/sys/kernel/random/uuid` is
			# Linux-only; this script runs on macOS, so we go straight to
			# the timestamp/pid fallback.
			doc_uuid="$(date -u +%Y%m%d%H%M%S)-$$-$RANDOM"
		fi
		local doc_namespace="http://spdx.org/spdxdocs/${DEVICE_ID}-${doc_uuid}"

		if ! jq -s --arg device_id "$DEVICE_ID" --arg namespace "$doc_namespace" '{
                SPDXID: "SPDXRef-DOCUMENT",
                spdxVersion: "SPDX-2.3",
                creationInfo: {
                    created: (now | strftime("%Y-%m-%dT%H:%M:%SZ")),
                    creators: ["Tool: sbom-audit-spdx"]
                },
                name: $device_id,
                dataLicense: "CC0-1.0",
                documentNamespace: $namespace,
                hasExtractedLicensingInfos: (
                    [.[].hasExtractedLicensingInfos[]?] |
                    group_by(.licenseId) | map(.[0])
                ),
                packages: ([.[].packages[]?] | unique_by(.SPDXID // (.name + "-" + (.versionInfo // "UNKNOWN") + "-" + (.downloadLocation // "UNKNOWN"))) |
                           map(
                               .filesAnalyzed = false |
                               del(.licenseInfoFromFiles, .packageVerificationCode, .hasFiles) |
                               if .versionInfo == "" then del(.versionInfo) else . end |
                               if .externalRefs then
                                   .externalRefs |= map(select(.referenceType != "cpe23Type"))
                               else . end |
                               if .externalRefs == [] then del(.externalRefs) else . end
                           )),
                relationships: [
                    {
                        spdxElementId: "SPDXRef-DOCUMENT",
                        relationshipType: "DESCRIBES",
                        relatedSpdxElement: (([.[].packages[]?] | unique_by(.SPDXID // (.name + "-" + (.versionInfo // "UNKNOWN") + "-" + (.downloadLocation // "UNKNOWN"))))[0].SPDXID // "NOASSERTION")
                    }
                ]
            } | if .hasExtractedLicensingInfos == [] then del(.hasExtractedLicensingInfos) else . end
        ' "${sboms_to_merge[@]}" >"$merged_sbom"; then
			echo "  ✗ jq merge failed for device SBOM" >&2
			exit 1
		fi

		if [ ! -s "$merged_sbom" ]; then
			echo "  ✗ jq produced empty output for device SBOM" >&2
			exit 1
		fi

		echo "  ✓ Merged ${#sboms_to_merge[@]} SBOMs" >&2
	fi

	local final_pkg_count
	final_pkg_count=$(jq '.packages | length' "$merged_sbom")
	echo "  ✓ Final SBOM: $final_pkg_count packages" >&2

	if [[ "$MODE" == test* ]]; then
		echo "  ✓ Saved to: $merged_sbom" >&2
	fi

	echo "$merged_sbom"
}

upload_sbom() {
	local sbom_file="$1"

	echo "→ Uploading SBOM..."

	# Calculate checksum
	local checksum
	checksum=$(shasum -a 256 "$sbom_file" | awk '{print $1}')

	# Build JSON payload safely using jq
	local json_payload
	json_payload=$(jq -n \
		--arg dev "$DEVICE_ID" \
		--arg sum "$checksum" \
		'{device_id: $dev, checksum: $sum}')

	# Pass auth token via --config file to keep it out of the process argument list
	local auth_config
	auth_config=$(mktemp)
	chmod 600 "$auth_config"
	printf 'header = "Authorization: %s"\n' "$SBOM_AUTH_TOKEN" >"$auth_config"

	# Request presigned URL from Lambda. Not retried: each presign mints
	# a fresh correlation_id + S3 key, so a transparent curl retry would
	# leak orphan presigns into logs/metrics without observable benefit.
	local presign_response
	presign_response=$(curl -sS -X POST "$LAMBDA_URL" \
		--max-time 60 \
		--connect-timeout 10 \
		--config "$auth_config" \
		-H "Content-Type: application/json" \
		-H "X-Device-ID: $DEVICE_ID" \
		-d "$json_payload") || {
		rm -f "$auth_config"
		echo "✗ Failed to request presigned URL" >&2
		return 1
	}
	rm -f "$auth_config"

	# Extract upload URL and correlation ID
	local upload_url correlation_id
	upload_url=$(echo "$presign_response" | jq -r '.upload_url')
	correlation_id=$(echo "$presign_response" | jq -r '.correlation_id // "unknown"')
	
	# Calculate HMAC signature using the same logic as the Go presignSignature function
	local sig
	if [ -z "$SBOM_PRESIGN_SECRET" ]; then
		echo "✗ SBOM_PRESIGN_SECRET environment variable not set" >&2
		return 1
	fi
	if command -v openssl &>/dev/null; then
		sig=$(printf '%s' "$checksum" | openssl dgst -sha256 -hmac "$SBOM_PRESIGN_SECRET" -hex | sed 's/^.* //')
	else
		echo "✗ openssl not available for HMAC signature calculation" >&2
		return 1
	fi

	if [ -z "$upload_url" ] || [ "$upload_url" = "null" ]; then
		echo "✗ Lambda returned invalid presigned URL response" >&2
		echo "  HTTP request succeeded but response did not contain upload_url" >&2
		return 1
	fi

	# Validate upload URL points to AWS S3 (prevent exfiltration via compromised Lambda)
	# Extract host from URL — only matches https://, so http:// is implicitly rejected
	local upload_host
	upload_host=$(printf '%s' "$upload_url" | sed -n 's|^https://\([^/]*\)/.*|\1|p')
	if [[ -z "$upload_host" || "$upload_host" != *.amazonaws.com ]]; then
		echo "✗ Presigned URL is not a valid HTTPS AWS endpoint" >&2
		return 1
	fi

	# Upload SBOM to S3 using presigned URL (with retry logic for transient failures)
	# IMPORTANT: Must include metadata headers matching presigned request
	# Use -w to capture HTTP status code, -o to suppress body output
	local http_code
	http_code=$(curl -sS -w '%{http_code}' -o /dev/null \
		--max-time 300 \
		--connect-timeout 10 \
		--retry 3 \
		--retry-delay 2 \
		-X PUT "$upload_url" \
		-H "Content-Type: application/json" \
		-H "x-amz-meta-device-id: $DEVICE_ID" \
		-H "x-amz-meta-checksum: $checksum" \
		-H "x-amz-meta-correlation-id: $correlation_id" \
		-H "x-amz-meta-sig: $sig" \
		-H "x-amz-server-side-encryption: AES256" \
		--data-binary "@$sbom_file") || {
		echo "✗ Upload request failed" >&2
		return 1
	}

	# Check HTTP status code (200-299 = success)
	if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
		echo "✗ Upload failed with HTTP $http_code" >&2
		return 1
	fi

	echo "✓ SBOM uploaded successfully"
	echo "  Device: $DEVICE_ID"
	echo "  Size: $(du -h "$sbom_file" | awk '{print $1}')"
	echo "  Checksum: ${checksum:0:16}..."
	echo "  Correlation ID: $correlation_id"
	echo "  HTTP Status: $http_code"

	return 0
}

cleanup_old_files() {
	if [[ "$MODE" == test* ]]; then
		# Skip cleanup in test mode
		return 0
	fi

	# Strict guardrails: Verify SBOM_DIR is set and is our directory
	if [ -z "$SBOM_DIR" ] || [ ! -d "$SBOM_DIR" ]; then
		echo "✗ SAFETY: SBOM_DIR not set or doesn't exist" >&2
		return 1
	fi

	# Verify SBOM_DIR is ~/.sbom-audit (production) or in TMPDIR (should never happen in production)
	if [[ "$SBOM_DIR" != "${HOME}/.sbom-audit" ]]; then
		echo "✗ SAFETY: SBOM_DIR is not ~/.sbom-audit: $SBOM_DIR" >&2
		return 1
	fi

	# Remove marker files older than 60 days (keep last 2 months)
	local old_markers
	old_markers=$(find "$SBOM_DIR" -maxdepth 1 -name ".last-upload-*" -type f -mtime +60 2>/dev/null | wc -l | tr -d ' ')

	# Remove stale SBOM files older than 1 day (should be uploaded or failed)
	local stale_sboms
	stale_sboms=$(find "$SBOM_DIR" -maxdepth 1 -name "*.spdx.json" -type f -mtime +1 2>/dev/null | wc -l | tr -d ' ')

	# Count intermediate files to clean
	local intermediate_files
	intermediate_files=$(find "$SBOM_DIR" -maxdepth 1 -type f \( -name "nix-*.spdx.json" -o -name "system-*.spdx.json" -o -name "device-*.spdx.json" \) 2>/dev/null | wc -l | tr -d ' ')

	if [ "$old_markers" -gt 0 ] || [ "$stale_sboms" -gt 0 ] || [ "$intermediate_files" -gt 0 ]; then
		echo "→ Cleaning up old files..."
	fi

	# Execute cleanup with maxdepth=1 (never recurse)
	if [ "$old_markers" -gt 0 ]; then
		find "$SBOM_DIR" -maxdepth 1 -name ".last-upload-*" -type f -mtime +60 -print -delete 2>/dev/null || true
		echo "  ✓ Removed $old_markers old marker file(s)"
	fi

	if [ "$stale_sboms" -gt 0 ]; then
		find "$SBOM_DIR" -maxdepth 1 -name "*.spdx.json" -type f -mtime +1 -print -delete 2>/dev/null || true
		echo "  ✓ Removed $stale_sboms stale SBOM file(s)"
	fi

	# Remove intermediate files (nix-*.spdx.json, system-*.spdx.json, device-*.spdx.json)
	if [ "$intermediate_files" -gt 0 ]; then
		find "$SBOM_DIR" -maxdepth 1 -type f \( -name "nix-*.spdx.json" -o -name "system-*.spdx.json" -o -name "device-*.spdx.json" \) -print -delete 2>/dev/null || true
		echo "  ✓ Removed $intermediate_files intermediate file(s)"
	fi

	if [ "$old_markers" -eq 0 ] && [ "$stale_sboms" -eq 0 ] && [ "$intermediate_files" -eq 0 ]; then
		echo "  ✓ No old files to clean"
	fi
}

test_mode_summary() {
	local sbom_file="$1"

	if [ ! -f "$sbom_file" ]; then
		echo "✗ SBOM file not found: $sbom_file" >&2
		return 1
	fi

	echo ""
	echo "=== Test Complete ==="
	echo ""
	echo "Final SBOM (single file with all packages):"
	echo "  Path: $sbom_file"
	echo "  Size: $(du -h "$sbom_file" 2>/dev/null | awk '{print $1}')"
	echo ""
	echo "SBOM validation:"

	# Validate SPDX fields
	local spdx_id spdx_version doc_namespace pkg_count
	spdx_id=$(jq -r '.SPDXID' "$sbom_file" 2>/dev/null)
	spdx_version=$(jq -r '.spdxVersion' "$sbom_file" 2>/dev/null)
	doc_namespace=$(jq -r '.documentNamespace' "$sbom_file" 2>/dev/null)
	pkg_count=$(jq '.packages | length' "$sbom_file" 2>/dev/null)

	echo "  SPDXID: $spdx_id"
	echo "  spdxVersion: $spdx_version"
	echo "  documentNamespace: $doc_namespace"
	echo "  packages: $pkg_count"
	echo ""

	# Show sample packages
	echo "Sample packages (first 5):"
	jq -r '.packages[0:5] | .[] | "  - \(.name) \(.versionInfo // "UNKNOWN")"' "$sbom_file" 2>/dev/null
	echo ""

	echo "✓ Single merged SBOM file created (intermediate files cleaned up)"
}

main() {
	# Validate Lambda URL configuration (required for production and test-upload modes)
	if [ "$MODE" != "test" ]; then
		if [ -z "$LAMBDA_URL" ]; then
			echo "✗ SBOM_LAMBDA_URL environment variable not set" >&2
			echo "  Configure in MDM custom-script environment variables" >&2
			echo "  Example: SBOM_LAMBDA_URL='https://abc123.lambda-url.us-east-1.on.aws/'" >&2
			exit 1
		fi
	fi

	# Validate authentication token (only required for production mode)
	# Test mode bypasses auth checks - no token needed
	if [ "$MODE" != "test" ]; then
		if [ -z "${SBOM_AUTH_TOKEN:-}" ]; then
			echo "✗ SBOM_AUTH_TOKEN environment variable not set" >&2
			echo "  This should be configured via MDM" >&2
			echo "  Use --test mode for local testing without token" >&2
			exit 1
		fi
		# Basic format check (expect 32+ printable chars)
		if [ ${#SBOM_AUTH_TOKEN} -lt 32 ]; then
			echo "⚠ Warning: SBOM_AUTH_TOKEN seems too short (${#SBOM_AUTH_TOKEN} chars, expected 32+)" >&2
			echo "  Continuing anyway - Lambda will reject if invalid" >&2
		fi
	fi

	# Acquire lockfile to prevent concurrent runs (macOS compatible)
	LOCKFILE="${SBOM_DIR}/.sbom.lock"
	# shellcheck disable=SC2174
	mkdir -p -m 700 "$SBOM_DIR"

	# Try to create lockfile exclusively (fails if exists)
	if ! (
		set -o noclobber
		echo $$ >"$LOCKFILE"
	) 2>/dev/null; then
		# Check if process is still running
		if [ -f "$LOCKFILE" ]; then
			local lock_pid
			lock_pid=$(cat "$LOCKFILE" 2>/dev/null)
			if [ -n "$lock_pid" ] && kill -0 "$lock_pid" 2>/dev/null; then
				# Check lock file age - if > 4 hours, assume stale even if PID alive
				local lock_age=0
				if command -v stat &>/dev/null; then
					if [[ "$(uname)" == "Darwin" ]]; then
						lock_age=$(($(date +%s) - $(stat -f %m "$LOCKFILE" 2>/dev/null || echo 0)))
					else
						lock_age=$(($(date +%s) - $(stat -c %Y "$LOCKFILE" 2>/dev/null || echo 0)))
					fi
				fi
				if [ "$lock_age" -gt 14400 ]; then
					echo "⚠ Removing stale lock (age: ${lock_age}s, PID: $lock_pid still alive but lock too old)" >&2
					rm -f "$LOCKFILE"
					if ! (
						set -o noclobber
						echo $$ >"$LOCKFILE"
					) 2>/dev/null; then
						echo "✗ Lock acquired by another process during stale cleanup; exiting" >&2
						exit 1
					fi
				else
					echo "✗ Another sbom-audit-spdx process is running (PID: $lock_pid); exiting" >&2
					exit 1
				fi
			else
				# Stale lockfile, remove and recreate with noclobber to prevent race
				rm -f "$LOCKFILE"
				if ! (
					set -o noclobber
					echo $$ >"$LOCKFILE"
				) 2>/dev/null; then
					echo "✗ Lock acquired by another process during stale cleanup; exiting" >&2
					exit 1
				fi
			fi
		else
			# Lockfile creation failed but file doesn't exist - filesystem issue
			echo "✗ Failed to create lockfile at $LOCKFILE (directory not writable?)" >&2
			exit 1
		fi
	fi

	# Clean up lockfile on exit and signals
	trap 'rm -f "$LOCKFILE"' EXIT INT TERM

	if [[ "$MODE" == test* ]]; then
		echo "=== SPDX SBOM Generation Test ==="
		echo "Output directory: $SBOM_DIR"
		echo ""
		echo "Checking dependencies..."
	fi

	# Distribute load to prevent thundering herd (production mode only)
	if [[ "$MODE" != test* ]] && [ -z "${SBOM_SKIP_DELAY:-}" ]; then
		local random_delay=$((RANDOM % 3600))
		echo "→ Waiting ${random_delay}s to distribute server load..."
		sleep "$random_delay"
	fi

	check_already_run

	# Clean up old files from previous runs
	cleanup_old_files

	ensure_homebrew || {
		echo "✗ Homebrew/Workbrew required but could not be installed" >&2
		echo "  Install manually: https://brew.sh or https://workbrew.com" >&2
		exit 1
	}
	ensure_jq || {
		echo "✗ jq is required but could not be installed" >&2
		exit 1
	}
	ensure_gnumfmt || true # Try to install, fall back to basic formatting if fails
	ensure_syft || {
		echo "✗ Syft is required but could not be installed" >&2
		exit 1
	}
	ensure_sbomnix || {
		echo "✗ sbomnix is required but could not be installed" >&2
		exit 1
	}
	ensure_pyspdxtools || {
		echo "✗ pyspdxtools is required for SPDX validation" >&2
		exit 1
	}

	if [[ "$MODE" == test* ]]; then
		echo ""
	fi

	local sbom_file
	sbom_file=$(generate_device_sbom) || exit 1

	# Validate SPDX document before upload/output
	echo ""
	validate_spdx "$sbom_file" || {
		echo "✗ SPDX validation failed - generated file may be invalid" >&2
		exit 1
	}

	if [[ "$MODE" == test* ]]; then
		# Clean up intermediate files in test mode too (with strict guardrails)
		if [ -n "$SBOM_DIR" ] && [ -d "$SBOM_DIR" ]; then
			find "$SBOM_DIR" -maxdepth 1 -type f \( \
				-name "nix-*.spdx.json*" -o \
				-name "system-*.spdx.json*" -o \
				-name "nix-pkg-*.spdx.json*" \
				\) ! -name "$(basename "$sbom_file")" -delete 2>/dev/null || true

			# Clean up sbomnix artifacts
			safe_delete_file "${SBOM_DIR}/sbom.cdx.json"
			safe_delete_file "${SBOM_DIR}/sbom.csv"
			safe_delete_file "${SBOM_DIR}/http_cache.sqlite"
		fi

		test_mode_summary "$sbom_file"

		# --test-upload: also upload to Lambda after showing test summary
		if [ "$MODE" = "test-upload" ]; then
			echo ""
			upload_sbom "$sbom_file" || exit 1
		fi
	else
		upload_sbom "$sbom_file" || exit 1

		# Mark as completed for this month (month-only format)
		local current_month
		current_month=$(date -u +%Y-%m)
		local marker_file="${SBOM_DIR}/.last-upload-${current_month}"
		if ! date -u +%Y-%m-%dT%H:%M:%SZ >"$marker_file" 2>/dev/null; then
			echo "⚠ Warning: Upload succeeded but monthly marker creation failed" >&2
			echo "  Next run may re-upload this month" >&2
			echo "  Marker path: $marker_file" >&2
		fi

		# Clean up SBOM file immediately after successful upload
		if [ -f "$sbom_file" ]; then
			safe_delete_file "$sbom_file"
			echo "✓ Cleaned up generated SBOM file"
		fi

		# Final cleanup of any remaining intermediate files (with strict guardrails)
		if [ -n "$SBOM_DIR" ] && [ -d "$SBOM_DIR" ] && [[ "$SBOM_DIR" == "${HOME}/.sbom-audit" ]]; then
			# Only delete our specific file patterns in our directory, never recurse
			find "$SBOM_DIR" -maxdepth 1 -type f \( \
				-name "nix-*.spdx.json" -o \
				-name "system-*.spdx.json" -o \
				-name "device-*.spdx.json" \
				\) -delete 2>/dev/null || true

			# Clean up sbomnix artifacts
			safe_delete_file "${SBOM_DIR}/sbom.cdx.json"
			safe_delete_file "${SBOM_DIR}/sbom.csv"
			safe_delete_file "${SBOM_DIR}/http_cache.sqlite"

			echo "✓ Cleaned up intermediate files"
		fi

		echo ""
		echo "=== SBOM Audit Complete ==="
	fi
}

main "$@"
